random_seed: 42

datasets:
  - coco-2017: {
      samples_number: 1,
      splits: {
        train: 0.8,
        valid: 0.2
      },
      stages: [fisheye, sam]
    }
  - open-images-v7: {
      splits: {
        valid: 100,
        train: 100,
        test: 100,
      },
      stages: [fisheye, sam]
    }
  - Pascal-VOC-2012-1: {
      samples_number: 1,
      splits: {
        train: 0.9,
        valid: 0.1,
      },
      stages: [fisheye, sam]
    }
  - Construction-Site-Safety-30: {
      samples_number: 1,
      splits: {
        train: 0.8,
        valid: 0.1,
        test: 0.1
      },
      stages: [fisheye, sam]
    }
  - WiderPerson: {
      samples_number: 1,
      splits: {
        train: 0.9,
        valid: 0.1,
      },
      stages: [fisheye, sam]
    }
  - Person-Detection-Fisheye-1: {
      samples_number: 1,
      splits: {
        train: 0.8,
        valid: 0.1,
        test: 0.1
      },
      stages: []
    }
  - Kitti: {
      samples_number: 1,
      splits: {
        train: 1.0
      },
      stages: [fisheye, sam]
    }

fisheye_params:
  distortion_params: {
    distort_limit: [2.8, 2.8],
    shift_limit: [10, 10],
    p: 0.5
  }
  horizontal_params: {
    p: 0.5
  }
  perspective_params: {
    scale: [0.1, 0.15],
    p: 0.5,
    keep_size: True
  }

sam_params:
  weights_path: sam_weights/sam_vit_h_4b8939.pth
  model_type: vit_h

sampled_yaml_file: data_yolo8.yaml
